version: '3.8'

services:
  vllm-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vllm-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # vLLM Configuration
      - VLLM_MODEL_PATH=/app/models
      - VLLM_HOST=0.0.0.0
      - VLLM_PORT=8000
      - VLLM_WORKER_USE_RAY=false
      - VLLM_DISABLE_LOG_STATS=false
      
      # GPU Configuration
      - CUDA_VISIBLE_DEVICES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      
      # Model Configuration (can be overridden)
      - MODEL_NAME=microsoft/DialoGPT-medium
      - MAX_MODEL_LEN=2048
      - GPU_MEMORY_UTILIZATION=0.9
      - TENSOR_PARALLEL_SIZE=1
      - PIPELINE_PARALLEL_SIZE=1
      
      # Performance Settings
      - BLOCK_SIZE=16
      - SWAP_SPACE=4
      - MAX_NUM_BATCHED_TOKENS=2048
      - MAX_NUM_SEQS=256
      
      # Logging
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      
    volumes:
      # Model storage
      - ./models:/app/models:rw
      - ./config:/app/config:ro
      - ./logs:/app/logs:rw
      
      # Cache directories for better performance
      - vllm-cache:/root/.cache
      - huggingface-cache:/root/.cache/huggingface
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Network configuration
    networks:
      - vllm-network

  # Optional: Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    container_name: vllm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vllm-network
    command: redis-server --appendonly yes

  # Optional: Monitoring with Prometheus metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: vllm-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - vllm-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  vllm-cache:
    driver: local
  huggingface-cache:
    driver: local
  redis-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  vllm-network:
    driver: bridge